config/routes.rb
Rails.application.routes.draw do
  get 'friendships/index'
    devise_for :users
    
    devise_scope :user do
        authenticated :user do
            root 'posts#index', as: :authenticated_root
        end

        unauthenticated do
            root 'devise/sessions#new', as: :unauthenticated_root
        end
    end

    # root "posts#index"
    # config/routes.rb
    get '/friendships/send_request', to: 'friendships#send_request'

    get '/friendships/friends_list', to: 'friendships#friends_list'

    get 'friendships/invitations', to: 'friendships#invitations'

    patch 'friendships/:id/accept_request', to: 'friendships#accept',  as: 'friendships_accept_request'

    delete 'friendships/:id/reject_request', to: 'friendships#reject', as: 'friendships_reject_request'

    # config/routes.rb


    resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/friendship.rb
class Friendship
    include Mongoid::Document
    include Mongoid::Timestamps
    field :senderId, type: String
    field :receiverId, type: String
    field :status, type: String
  
    belongs_to :sender, class_name: 'User', foreign_key: 'senderId'
    belongs_to :receiver, class_name: 'User', foreign_key: 'receiverId'
  
end

app/models/post.rb
class Post
    include Mongoid::Document
    include Mongoid::Timestamps
    field :title, type: String
    field :body, type: String
    field :user_id, type: String

    belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time


  def to_s
    email
  end

  ## Rememberable
  field :remember_created_at, type: Time

  has_many :post
  has_many :friendship, foreign_key: :senderId

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  include Mongoid::Timestamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def index
        @query = params[:query]
        @users = []
        @sent_requests = []
      
        if @query.present?
            accepted_friend_ids = Friendship.where(senderId: current_user.id, status: "accepted").pluck(:receiverId)
            accepted_friend_ids_1 = Friendship.where(receiverId: current_user.id, status: "accepted").pluck(:senderId)
            received_request_ids = Friendship.where(receiverId: current_user.id, status: "pending").pluck(:senderId)
            
            @users = User.where('email': /#{@query}/)
                        .where.not(id: current_user.id)
                        .reject { |user| accepted_friend_ids.include?(user.id) || accepted_friend_ids_1.include?(user.id) || received_request_ids.include?(user.id) }

            @sent_requests = current_user.friendship.where(status: "pending").pluck(:receiverId)
        end
    end
      

    def send_request
        sender = User.find(params[:senderId])
        receiver = User.find(params[:receiverId])

        Friendship.create(senderId: sender.id, receiverId: receiver.id, status: "pending")
        redirect_to friendships_index_path(notice: 'Friend request sent successfully!')
        
    end

    def friends_list
        requested = Friendship.where(receiverId: current_user.id, status: "accepted").pluck(:senderId)
        sent = Friendship.where(senderId: current_user.id, status: "accepted").pluck(:receiverId)
        friend_ids = requested + sent
        @friends = User.in(id: friend_ids)
    end  
    
    def invitations
        @received_requests = Friendship.where(receiverId: current_user.id, status: "pending")
    end
    
    def accept
        friendship = Friendship.find(params[:id])
        friendship.update(status: "accepted")
        redirect_to friendships_invitations_path(notice: 'Friend request accepted successfully!')
    end
    
    def reject
        friendship = Friendship.find(params[:id])
        friendship.destroy
        redirect_to friendships_invitations_path(notice: 'Friend request rejected successfully!')
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    # @posts = Post.all
    @posts = current_user.post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/friendships/friends_list.html.erb
<%= stylesheet_link_tag "list.css", :media => "all" %>

<div class="backbutton">
  <%= link_to "Go Back", authenticated_root_path, class: "custom-link" %>
</div>

<div class="header">
  <div class="list">
    <%= link_to "Friends List", friendships_friends_list_path, class: "custom-link" %>
  </div>
    
  <div class="requests">
    <%= link_to "Send Request", friendships_index_path, class: "custom-link" %>
  </div>

  <div class="invites">
    <%= link_to "See Invites", friendships_invitations_path, class: "custom-link" %>
  </div>
</div>

<h1 class = "list-header">Friends List</h1>

<% if @friends.present? %>
  <ul class="centered-list">
    <% @friends.each do |friend| %>
      <li><%= friend %></li>
    <% end %>
  </ul>
<% else %>
  <p class = "no-friends">No friends available.</p>
<% end %>

app/views/friendships/index.html.erb
<%= stylesheet_link_tag "friendship_index.css", :media => "all" %>

<% if params[:notice] %>
  <div class="notice">
    <%= params[:notice] %>
  </div>
<% end %>


<div class ="backbutton">
    <%= link_to "Go Back"  ,  authenticated_root_path, class: "custom-link" %>
</div>

<div class= "header">

    <div class ="list">
        <%= link_to "Friends List"  ,  friendships_friends_list_path, class: "custom-link" %>
    </div>

    <div class ="requests">
        <%= link_to "Send Request"  ,  friendships_index_path, class: "custom-link" %>
    </div>

    <div class = "invites">
        <%= link_to "See Invites"  ,  friendships_invitations_path, class: "custom-link" %>
    </div>

</div>

<div class="search-container">

  <form action="<%= friendships_index_path %>" method="GET" class="search-form">

    <input type="text" name="query" placeholder="Search..." class="search-input">

    <button type="submit" class="search-button">Search</button>
  
  </form>

</div>


<h2 class="search-header">Search Results</h2>

<ul class="search-results">
    <% if @users.present? %>
        <% @users.each do |user| %>
            <li class="search-result">
                <div class="user-info">
                    <p class="user-email"><%= user.email %></p>
                    <% if @sent_requests.include?(user.id) %>
                        <span class="sent-button">Sent</span>
                    <% else %>
                        <%= link_to 'Send Friend Request', friendships_send_request_path(senderId: current_user.id, receiverId: user.id, status: "pending"), method: :get, class: 'send-request-link' %>
                    <% end %>
                </div>
            </li>
        <% end %>
    <% else %>
        <p class="no-results-message">No results available.</p>
    <% end %>

</ul>

app/views/friendships/invitations.html.erb
<%= stylesheet_link_tag "friendship_invites.css", :media => "all" %>

<div class ="backbutton">
    <%= link_to "Go Back"  ,  authenticated_root_path, class: "custom-link" %>
</div>

<div class= "header">

    <div class ="list">
        <%= link_to "Friends List"  ,  friendships_friends_list_path, class: "custom-link" %>
    </div>
    
    <div class ="requests">
        <%= link_to "Send Request"  ,  friendships_index_path, class: "custom-link" %>
    </div>

    <div class = "invites">
        <%= link_to "See Invites"  ,  friendships_invitations_path, class: "custom-link" %>
    </div>


</div>

<h1 class="inv-header">Friend Invitations</h1>
<% if @received_requests.any? %>
  <ul>
    <% @received_requests.each do |request| %>
      <li>
        <div class="friend-request">
          <p class="friend-email"><%= request.sender.email %></p>
          <div class="friend-actions">
            <%= button_to 'Accept', friendships_accept_request_path(request.id), method: :patch, class: 'btn-accept' %>
            <%= button_to 'Reject', friendships_reject_request_path(request.id), method: :delete, class: 'btn-reject' %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="no-friends">No friend invitations found.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ToDoApp</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %> 
    </head>

    <body>
        <%= yield %>
    </body>
</html>

app/views/posts/_form.html.erb
<%= stylesheet_link_tag "form.css", :media => "all" %>  

<div class="container">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div class="error-container">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div id="form-container">
      <div class="container-label">
        <%= form.label :title %>
      </div>
      <div class="container-field">
        <%= form.text_field :title, class: "text-input" %>
      </div>

      <div class="container-label">
        <%= form.label :Note %>
      </div>
      <div class="container-field">
        <%= form.text_area :body, class: "textarea-input" %>
      </div>

      <div class="container-field" id="user-id">
        <%= form.label :user %>
        <%= form.text_area :user_id, value: current_user.id, class: "hidden-input" %>
      </div>

      <div class="container-field">
        <%= form.submit "Create", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<%= stylesheet_link_tag "post.css", :media => "all" %>

<div class='post'>
  <div id="<%= dom_id post %>">
    <div id='post-inner'>
      <div class='post-content'>
        <div class='title'>
          <strong>Title:</strong>
          <%= post.title %>
        </div>

        <div class='body'>
          <strong>Body:</strong>
          <%= post.body %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag "edit.css", :media => "all" %>
<div class="container">
    <h1 class="title">Edit Note</h1>

    <%= render "form", post: @post %>

    <br>

    <div class="links">
        <%= link_to "Show this post", @post %> |
        <%= link_to "Back to posts", posts_path %>
    </div>
</div>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>

<%= stylesheet_link_tag "index.css", :media => "all" %>

<div class="container">
  <div id="links-container">
    <div id="profile">
      <div id="edit-profile">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "button-link" %>
      </div>
      <div id="friends">
        <%= link_to "Friendships", friendships_friends_list_path, class: "button-link" %>
      </div>
      <div id="logout">
        <%= button_to "Log out", destroy_user_session_path, method: :delete, data: { turbo: false }, class: "button-link" %>
      </div>
    </div>
  </div>

  <div id="header">
    <h1>My Notes</h1>
  </div>

    <div id="new-post">
      <%= link_to "Add Note", new_post_path, class: "button-link" %>
    </div>

  <div id="posts">
    <% @posts.each do |post| %>
    <div class="post-container">
      <div class="post-render">
        <%= render post %>
      </div>

      <p class="show">
        <%= link_to "Show", post %>
      </p>
    </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "new.css", :media => "all" %> 

<div class="container">
  <h1 class="title">New Note</h1>

  <%= render "form", post: @post %>

  <div class="back-link">
    <%= link_to "Back to posts", posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "show.css", :media => "all" %>

<p class="notice"><%= notice %></p>

<div class="container">
  <h1>Note</h1>
  <div id="render-post">
    <%= render @post %>
  </div>

  <div id="bottom">
    <div id="note-manage">
      <%= link_to "Edit this post", edit_post_path(@post) %> |
      <%= link_to "Back to posts", posts_path %>
    </div>
        
    <div id="destroy">
      <%= button_to "Destroy this post", @post, method: :delete, class: "destroy-button" %>
    </div>
  </div>
</div>